config/routes.rb
Rails.application.routes.draw do
  resources :parksons
  resources :promos
  resources :publics
  resources :logins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/login.rb
class Login
  include Mongoid::Document
  field :email, type: String
  field :pass, type: String
end

app/models/parkson.rb
class Parkson
  include Mongoid::Document
end

app/models/promo.rb
class Promo
  include Mongoid::Document
end

app/models/public.rb
class Public
  include Mongoid::Document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:email, :pass)
    end
end

app/controllers/parksons_controller.rb
class ParksonsController < ApplicationController
  before_action :set_parkson, only: [:show, :edit, :update, :destroy]

  # GET /parksons
  # GET /parksons.json
  def index
    @parksons = Parkson.all
  end

  # GET /parksons/1
  # GET /parksons/1.json
  def show
  end

  # GET /parksons/new
  def new
    @parkson = Parkson.new
  end

  # GET /parksons/1/edit
  def edit
  end

  # POST /parksons
  # POST /parksons.json
  def create
    @parkson = Parkson.new(parkson_params)

    respond_to do |format|
      if @parkson.save
        format.html { redirect_to @parkson, notice: 'Parkson was successfully created.' }
        format.json { render :show, status: :created, location: @parkson }
      else
        format.html { render :new }
        format.json { render json: @parkson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parksons/1
  # PATCH/PUT /parksons/1.json
  def update
    respond_to do |format|
      if @parkson.update(parkson_params)
        format.html { redirect_to @parkson, notice: 'Parkson was successfully updated.' }
        format.json { render :show, status: :ok, location: @parkson }
      else
        format.html { render :edit }
        format.json { render json: @parkson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parksons/1
  # DELETE /parksons/1.json
  def destroy
    @parkson.destroy
    respond_to do |format|
      format.html { redirect_to parksons_url, notice: 'Parkson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parkson
      @parkson = Parkson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parkson_params
      params.fetch(:parkson, {})
    end
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  before_action :set_promo, only: [:show, :edit, :update, :destroy]

  # GET /promos
  # GET /promos.json
  def index
    @promos = Promo.all
  end

  # GET /promos/1
  # GET /promos/1.json
  def show
  end

  # GET /promos/new
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
  end

  # POST /promos
  # POST /promos.json
  def create
    @promo = Promo.new(promo_params)

    respond_to do |format|
      if @promo.save
        format.html { redirect_to @promo, notice: 'Promo was successfully created.' }
        format.json { render :show, status: :created, location: @promo }
      else
        format.html { render :new }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promos/1
  # PATCH/PUT /promos/1.json
  def update
    respond_to do |format|
      if @promo.update(promo_params)
        format.html { redirect_to @promo, notice: 'Promo was successfully updated.' }
        format.json { render :show, status: :ok, location: @promo }
      else
        format.html { render :edit }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo.destroy
    respond_to do |format|
      format.html { redirect_to promos_url, notice: 'Promo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo
      @promo = Promo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promo_params
      params.fetch(:promo, {})
    end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  before_action :set_public, only: [:show, :edit, :update, :destroy]

  # GET /publics
  # GET /publics.json
  def index
    @publics = Public.all
  end

  # GET /publics/1
  # GET /publics/1.json
  def show
  end

  # GET /publics/new
  def new
    @public = Public.new
  end

  # GET /publics/1/edit
  def edit
  end

  # POST /publics
  # POST /publics.json
  def create
    @public = Public.new(public_params)

    respond_to do |format|
      if @public.save
        format.html { redirect_to @public, notice: 'Public was successfully created.' }
        format.json { render :show, status: :created, location: @public }
      else
        format.html { render :new }
        format.json { render json: @public.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publics/1
  # PATCH/PUT /publics/1.json
  def update
    respond_to do |format|
      if @public.update(public_params)
        format.html { redirect_to @public, notice: 'Public was successfully updated.' }
        format.json { render :show, status: :ok, location: @public }
      else
        format.html { render :edit }
        format.json { render json: @public.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publics/1
  # DELETE /publics/1.json
  def destroy
    @public.destroy
    respond_to do |format|
      format.html { redirect_to publics_url, notice: 'Public was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_public
      @public = Public.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def public_params
      params.fetch(:public, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/parksons_helper.rb
module ParksonsHelper
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Untitled</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logins/_form.html.erb
<%= form_with(model: login, local: true) do |form| %>
  <% if login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :login_email %>
  </div>

  <div class="field">
    <%= form.label :pass %>
    <%= form.text_field :pass, id: :login_pass %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing Login</h1>

<%= render 'form', login: @login %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<%= javascript_include_tag "/app/javascript/components/Signin.js" %>

<p id="notice"><%= notice %></p>

<h1>Logins</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Pass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.email %></td>
        <td><%= login.pass %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login', new_login_path %>

<%= react_component 'Main' %>

app/views/logins/new.html.erb
<h1>New Login</h1>

<%= render 'form', login: @login %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @login.email %>
</p>

<p>
  <strong>Pass:</strong>
  <%= @login.pass %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>

app/views/parksons/_form.html.erb
<%= form_with(model: parkson, local: true) do |form| %>
  <% if parkson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parkson.errors.count, "error") %> prohibited this parkson from being saved:</h2>

      <ul>
      <% parkson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parksons/edit.html.erb
<h1>Editing Parkson</h1>

<%= render 'form', parkson: @parkson %>

<%= link_to 'Show', @parkson %> |
<%= link_to 'Back', parksons_path %>

app/views/parksons/index.html.erb
<html>
<head>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body style="margin:0">
<%= react_component("Parksons") %>
<%= javascript_include_tag "bootstrap.min.js" %>

</body>
</html>

app/views/parksons/new.html.erb
<h1>New Parkson</h1>

<%= render 'form', parkson: @parkson %>

<%= link_to 'Back', parksons_path %>

app/views/parksons/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_parkson_path(@parkson) %> |
<%= link_to 'Back', parksons_path %>

app/views/promos/_form.html.erb
<%= form_with(model: promo, local: true) do |form| %>
  <% if promo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(promo.errors.count, "error") %> prohibited this promo from being saved:</h2>

      <ul>
      <% promo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/promos/edit.html.erb
<h1>Editing Promo</h1>

<%= render 'form', promo: @promo %>

<%= link_to 'Show', @promo %> |
<%= link_to 'Back', promos_path %>

app/views/promos/index.html.erb
<html>
<head>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body style="margin:0">
<%= react_component("Promos") %>
<%= javascript_include_tag "bootstrap.min.js" %>

</body>
</html>

app/views/promos/new.html.erb
<h1>New Promo</h1>

<%= render 'form', promo: @promo %>

<%= link_to 'Back', promos_path %>

app/views/promos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_promo_path(@promo) %> |
<%= link_to 'Back', promos_path %>

app/views/publics/_form.html.erb
<%= form_with(model: public, local: true) do |form| %>
  <% if public.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(public.errors.count, "error") %> prohibited this public from being saved:</h2>

      <ul>
      <% public.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/publics/edit.html.erb
<h1>Editing Public</h1>

<%= render 'form', public: @public %>

<%= link_to 'Show', @public %> |
<%= link_to 'Back', publics_path %>

app/views/publics/index.html.erb
<html>
<head>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body style="margin: 0">
<%= react_component("LandingPage") %>
<%= react_component("Testing") %>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<%= javascript_include_tag "bootstrap.min.js" %>
<!--Script for Carousel-->
<script>
    $('.carousel[data-type="multi"] .carousel-item').each(function () {
        var next = $(this).next();
        if (!next.length) {
            next = $(this).siblings(':first');
        }
        next.children(':first-child').clone().appendTo($(this));
        for (var i = 0; i < 2; i++) {
            next = next.next();
            if (!next.length) {
                next = $(this).siblings(':first');
            }
            next.children(':first-child').clone().appendTo($(this));
        }
    });
</script>
</body>
</html>

app/views/publics/new.html.erb
<h1>New Public</h1>

<%= render 'form', public: @public %>

<%= link_to 'Back', publics_path %>

app/views/publics/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_public_path(@public) %> |
<%= link_to 'Back', publics_path %>